// GENERATED by scripts/select-view.mjs — do not edit; the next build overwrites it.
// VIEW_ID=NDE_TEST selects family "nde".
export { map as selectorComponentMap } from '../views/nde/component-map';
